id: '905beb51-0b18-40b1-9bcb-08dd9c3f3d0a'
name: 'C3-X-DB-FI'
description: ''
version: 'v1.5'
configuration:
  id: 'biGENIUS.Implementation.Generator.Stage.Spark.Databricks.File'
  version: '1.9.4'
sourceSystems:
  - id: '98010e5e-da81-4d43-adfb-042cfa3d5182'
    name: 'AdventureWorks'
    description: 'This is the Source system for the Adventure Works parquet files'
    sourceSystemTypeId: 'c5e55725-184f-4c60-a22d-70cb5d6fe513'
propertyValues:
  - propertyId: '59eca19a-3bec-4169-85fd-41331f6fac3a'
    value: 'true'
